services:
  db:
    image: postgres:15
    container_name: marcenaria_postgres
    environment:
      POSTGRES_USER: marcenaria_user
      POSTGRES_PASSWORD: marcenaria_pass
      POSTGRES_DB: marcenaria_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: